import { StyleSheet } from "react-native";
import {
  ColorLight,
  ColorDark,
  FontSize,
  FontFamily,
  Padding,
  Border,
} from "../../GlobalStyles";

const stylesLight = StyleSheet.create({
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderWidth: 0,
    borderRadius: 8,
    padding: 8,
    marginBottom: 4,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: ColorLight.white,
  },
  inactiveDot: {
    backgroundColor: "gray",
  },
  carouselContainer: {
    position: "relative",
    width: "100%",
    aspectRatio: 18 / 9,
    flexDirection: "row",
  },
  ratingContainer: {
    justifyContent: "center", // Centers children vertically
    alignItems: "center", // Centers children horizontally
    position: "absolute", // So the text can be positioned absolutely
    right: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,

    // Android elevation
    elevation: 5,
  },
  ratingImage: {
    // Width and height as per your requirement
    width: 33,
    height: 52,
  },
  ratingText: {
    color: ColorLight.white,
    fontSize: FontSize.headline3_size,
    fontFamily: FontFamily.medium,
    position: "absolute", // Positions text over the image
  },
  frameParentBooking: {
    height: 250,
    marginTop: 24,
    marginLeft: 24,
    marginRight: 24,
    overflow: "hidden",
    borderWidth: 0,
    borderRadius: 8,
    borderColor: "black",
  },
  frameViewBooking: {
    height: 80,
    borderBottomRightRadius: Border.br_5xs,
    borderBottomLeftRadius: Border.br_5xs,
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 12,
    backgroundColor: ColorLight.darkslategray_100,
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  dateGroup: {
    marginTop: 32,
    borderBottomWidth: 2,
    borderBottomColor: ColorLight.darkslategray_100,
    paddingBottom: 32,
  },
  dateHeading: {
    fontSize: 18,
    fontFamily: FontFamily.medium,
    color: ColorLight.text,
    marginLeft: 24,
  },
  disabledText: {
    color: "grey",
    opacity: 0.5,
  },
  disabledDay: {
    opacity: 0.6,
  },
  calendar: {
    padding: 10,
    backgroundColor: ColorLight.darkslategray_100,
    borderWidth: 0,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,

    // Android elevation
    elevation: 5,
  },
  monthSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 32,
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
    alignItems: "center",
  },
  yearSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
    alignItems: "center",
  },
  selectorText: {
    fontSize: 18,
    color: ColorLight.text,
    fontFamily: FontFamily.regular,
    padding: 5,
  },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
  },
  dayOfWeek: {
    width: 32,
    textAlign: "center",
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
    marginBottom: 16,
  },
  daysContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  day: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
    marginHorizontal: 10,
  },
  dayText: {
    textAlign: "center",
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
  },
  selectedDay: {
    backgroundColor: ColorLight.accentColor,
    borderRadius: 8,
    color: ColorLight.text,
    fontSize: 14,
    fontFamily: FontFamily.regular,
  },
  servicesContainer: {
    width: "85%",
    //height: "50%",
    borderWidth: 0,
    borderRadius: 16,
    position: "absolute",
    //top: 152,
    backgroundColor: ColorLight.darkslategray_100,
    flex: 1,
    flexDirection: "column",
    //alignItems: "center",
    padding: 24,
    paddingTop: 8,
    color: ColorLight.text,
  },
  frameDetailsImage: {
    //paddingTop: Padding.p_5xs,
    //alignSelf: "stretch",
    //justifyContent: "space-between",
    //flex: 1,
    //overflow: "hidden",
    //borderWidth: 0,
    width: "100%",
    aspectRatio: 18 / 9,
  },
  currentLocation: {
    flex: 0,
    flexDirection: "row",
    paddingTop: 24,
    alignItems: "center",
  },
  locationSearch: {
    paddingLeft: 44,
    paddingRight: 78,
    fontSize: 16,
    color: ColorLight.white,
    borderRadius: 32,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    height: 40,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    paddingVertical: 0,
    backgroundColor: ColorLight.darkslategray_100,
    alignItems: "center",
    paddingHorizontal: Padding.p_base,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  locationHeader: {
    //padding: Padding.p_base,
    /*paddingLeft: 16,
    paddingRight: 16,*/
    left: 0,
    right: 0,
    backgroundColor: ColorLight.background,
    //height: 116,
  },
  locationOverlay: {
    width: "100%",
    height: "100%",
    borderWidth: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    position: "absolute",
    top: 120,
    backgroundColor: ColorLight.background,
    flex: 1,
    flexDirection: "column",
    //alignItems: "center",
    paddingTop: 24,
    paddingLeft: 24,
    paddingRight: 24,
  },
  overlay: {
    width: "85%",
    //height: "50%",
    borderWidth: 0,
    borderRadius: 16,
    position: "absolute",
    top: 152,
    backgroundColor: ColorLight.background,
    flex: 1,
    flexDirection: "column",
    //alignItems: "center",
    padding: 24,
  },
  childLayout: {
    marginTop: 7,
    height: 4,
    borderRadius: Border.br_5xs,
    width: 100,
  },
  type1: {
    fontSize: FontSize.size_xs,
    height: 16,
    width: 100,
    display: "flex",
    fontFamily: FontFamily.regular,
    textAlign: "center",
    color: ColorLight.lightGray,
    letterSpacing: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  typeChild: {
    backgroundColor: ColorDark.accentColor,
    height: 4,
    borderRadius: Border.br_5xs,
  },
  registrationChild: {
    backgroundColor: ColorLight.lightGray,
  },
  doneChild: {
    backgroundColor: ColorLight.lightGray,
  },
  stationBar: {
    top: 64,
    right: 28,
    left: 28,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    justifyContent: "space-between",
    flexDirection: "row",
    shadowOpacity: 1,
    elevation: 4,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    position: "absolute",
  },
  arrowBack: {
    color: "black",
  },
  errorText: {
    color: ColorDark.text,
    fontSize: 16,
    fontFamily: FontFamily.bold,
    textAlign: "center",
  },
  errorContainer: {
    height: 50,
    width: 296,
    backgroundColor: "#db0f27",
    justifyContent: "center",
    borderWidth: 0,
    borderRadius: 8,
    margin: 16,
    marginTop: 0,
  },
  signInButton: {
    width: 296,
    height: 35,
    backgroundColor: ColorDark.accentColor,
    fontSize: 16,
    color: ColorDark.white,
    fontFamily: FontFamily.regular,
    borderWidth: 0,
    borderRadius: 8,
    justifyContent: "center",
    margin: 8,
    marginTop: 32,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  authContainer: {
    backgroundColor: "#fff",
    height: "100%",
    width: "100%",
    flex: 1,
    justifyContent: "center",
  },
  formInput: {
    backgroundColor: ColorDark.white,
    color: "black",
    borderWidth: 0,
    borderRadius: 8,
    width: 296,
    height: 40,
    fontFamily: FontFamily.regular,
    fontSize: 16,
    paddingLeft: 16,
    margin: 8,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  formInputPassword: {
    backgroundColor: ColorDark.white,
    color: "black",
    borderWidth: 0,
    borderRadius: 8,
    width: 256,
    height: 40,
    fontFamily: FontFamily.regular,
    fontSize: 16,
    paddingLeft: 16,
    marginRight: 4,
  },
  signInHeader: {
    textAlign: "center",
    fontSize: 32,
    fontFamily: FontFamily.bold,
    color: ColorDark.accentColor,
    marginBottom: 32,
  },
  welcomeContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  welcomeText: {
    color: ColorDark.text,
    fontFamily: FontFamily.bold,
    //top:252,
    flexWrap: "wrap",
    fontSize: 48,
    letterSpacing: -0.5,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.15)",
    textShadowOffset: {
      width: 0,
      height: 0,
    },
    textShadowRadius: 4,
    position: "absolute",
    bottom: 52,
    width: "100%",
  },
  textDescription: {
    fontFamily: FontFamily.regular,
    color: "#656565",
    fontSize: 16,
    textAlign: "center",
    marginTop: 52,
    width: 213,
  },
  signIn: {
    width: 184,
    height: 45,
    backgroundColor: ColorDark.accentColor,
    borderWidth: 0,
    borderRadius: 12,
    justifyContent: "center",
    marginTop: 32,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  signInText: {
    color: ColorDark.text,
    fontFamily: FontFamily.medium,
    textAlign: "center",
    fontSize: 16,
  },
  signUp: {
    width: 184,
    height: 45,
    backgroundColor: "#fff",
    borderWidth: 0,
    borderRadius: 12,
    justifyContent: "center",
    marginTop: 16,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  signUpText: {
    color: "#656565",
    fontFamily: FontFamily.medium,
    textAlign: "center",
    fontSize: 16,
  },

  fullScreen: {
    flex: 1,
  },
  likeButton: {
    backgroundColor: ColorLight.accentColor,
    borderWidth: 3,
    borderColor: ColorLight.accentColor,
    borderRadius: 10,
    marginRight: 2,
  },
  location: {
    flex: 0,
    flexDirection: "row",
    paddingTop: 16,
    alignItems: "center",
    width: 250,
    //width: "100%",
    justifyContent: "center",
  },
  locationIcon: {},
  searchImage: {
    padding: 10,
    paddingLeft: 16,
    position: "absolute",
    top: 0,
    zIndex: 1,
  },
  searchFilter: {
    padding: 10,
    position: "absolute",
    top: 0,
    right: 8,
    zIndex: 1,
  },
  containerLogin: {
    flex: 1,
    backgroundColor: "#fff",
  },
  container: {
    flex: 1,
    backgroundColor: ColorLight.background,
  },
  header: {
    padding: Padding.p_base,
    paddingLeft: 24,
    paddingRight: 24,
    left: 0,
    right: 0,
    backgroundColor: ColorLight.background,
    height: 116,
  },
  androidBg: {
    backgroundColor: ColorLight.darkgray,
    alignSelf: "stretch",
  },
  iconFlexBox: {
    justifyContent: "flex-end",
    alignItems: "center",
  },
  searchTypo: {
    marginTop: 5,
    height: 9,
    fontWeight: "500",
    fontSize: FontSize.caption_size,
    justifyContent: "center",
    display: "flex",
    fontFamily: FontFamily.regular,
    alignItems: "center",
  },
  bookedClr: {
    color: ColorLight.white,
    textAlign: "center",
    letterSpacing: 0,
  },
  navBarUpperSpaceBlock: {
    paddingVertical: 0,
    alignSelf: "stretch",
  },
  upperBarPosition: {
    left: 0,
    position: "absolute",
  },
  frameContainerFlexBox: {
    paddingRight: Padding.p_5xs,
    alignItems: "center",
    flexDirection: "row",
  },
  search1Typo: {
    fontSize: FontSize.body1_size,
    color: ColorLight.white,
    textAlign: "center",
    fontFamily: FontFamily.regular,
    fontWeight: "500",
    letterSpacing: 0,
  },
  search1FlexBox: {
    justifyContent: "center",
    alignItems: "center",
  },
  textTypo: {
    textAlign: "left",
    fontFamily: FontFamily.medium,
    color: ColorLight.white,
    display: "flex",
    fontWeight: "500",
    alignItems: "center",
  },
  address: {
    letterSpacing: 0.4,
    fontSize: 14,
    textAlign: "left",
    color: ColorLight.text,
    display: "flex",
    alignItems: "center",
  },
  type: {
    letterSpacing: 0.4,
    fontSize: 10,
    textAlign: "left",
    color: ColorLight.text,
    display: "flex",
    alignItems: "center",
  },
  distance: {
    letterSpacing: 0.4,
    fontSize: 10,
    textAlign: "right",
    color: ColorLight.text,
    display: "flex",
    alignItems: "center",
  },
  bookWrapperShadowBox: {
    elevation: 4,
    shadowRadius: 4,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    height: 32,
  },
  bookWrapperShadowBox1: {
    elevation: 4,
    shadowRadius: 4,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    height: 24,
  },
  iconSearchNormal1: {
    width: 21,
    height: 21,
  },
  search: {
    color: ColorLight.accentColor,
    width: 34,
    textAlign: "center",
    marginTop: 5,
    height: 9,
    fontWeight: "500",
    letterSpacing: 0,
    fontSize: FontSize.caption_size,
  },
  searchIcon: {
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: 0,
    height: 44,
    justifyContent: "flex-end",
    width: 105,
    borderRadius: Border.br_5xs,
    backgroundColor: ColorLight.darkslategray_200,
  },
  iconCalendar: {
    width: 20,
    height: 22,
  },
  booked: {
    width: 37,
    marginTop: 5,
    height: 9,
    fontWeight: "500",
    fontSize: FontSize.caption_size,
    justifyContent: "center",
    display: "flex",
    fontFamily: FontFamily.regular,
    alignItems: "center",
    color: ColorLight.white,
  },
  bookedIcon: {
    width: 106,
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: 0,
    height: 44,
    justifyContent: "flex-end",
    borderRadius: Border.br_5xs,
  },
  iconProfileCircle: {
    width: 22,
    height: 22,
  },
  profile: {
    width: 31,
    marginTop: 5,
    height: 9,
    fontWeight: "500",
    fontSize: FontSize.caption_size,
    justifyContent: "center",
    display: "flex",
    fontFamily: FontFamily.regular,
    alignItems: "center",
    color: ColorLight.white,
  },
  profileIcon: {
    borderRadius: 9,
    paddingVertical: Padding.p_9xs,
    paddingHorizontal: 0,
    height: 44,
    justifyContent: "flex-end",
    width: 105,
  },
  navBarBottom: {
    bottom: 0,
    paddingVertical: 3,
    paddingHorizontal: Padding.p_base,
    flexDirection: "row",
    backgroundColor: ColorLight.darkslategray_200,
    left: 0,
    right: 0,
    justifyContent: "space-between",
    position: "absolute",
  },
  booking: {
    fontSize: 35,
    fontFamily: FontFamily.ribeyeMarrowRegular,
    width: 219,
    display: "none",
  },
  pngwing2Icon: {
    width: 40,
    height: 13,
    display: "none",
    top: 0,
  },
  logo: {
    width: 0,
    height: 0,
  },
  searchFill0Wght400Grad0OpsIcon: {
    width: 19,
    height: 18,
  },
  search1: {
    width: 71,
    height: 19,
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
    fontSize: FontSize.body1_size,
  },
  searchFill0Wght400Grad0OpsParent: {
    flex: 1,
  },
  iconSetting4: {
    width: 13,
    height: 12,
  },
  navBarUpper: {
    paddingLeft: 44,
    paddingRight: 44,
    fontSize: 16,
    fontFamily: FontFamily.regular,
    color: ColorLight.white,
    borderRadius: 32,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    height: 40,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    paddingVertical: 0,
    backgroundColor: ColorLight.darkslategray_100,
    alignItems: "center",
    paddingHorizontal: Padding.p_base,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  iconLocation: {
    width: 16,
    height: 19,
  },
  chooseYourLocation: {
    marginLeft: 7,
  },
  iconArrowDown1: {
    width: 6,
    height: 3,
    marginLeft: 7,
  },
  iconLocationParent: {
    height: 23,
    marginTop: 16,
    justifyContent: "center",
    flexDirection: "row",
  },
  upperBar: {
    top: 0,
    padding: Padding.p_base,
    left: 0,
    position: "absolute",
    justifyContent: "flex-end",
    right: 0,
    backgroundColor: ColorLight.gray,
  },
  frameChild: {
    width: 49,
    zIndex: 0,
    height: 24,
    tintColor: ColorDark.accentColor,
  },
  text: {
    top: -22,
    left: 8,
    fontSize: FontSize.headline3_size,
    width: 27,
    height: 18,
    zIndex: 1,
    letterSpacing: 0,
    textAlign: "left",
    textShadowColor: "rgba(0, 0, 0, 0.15)",
    textShadowOffset: {
      width: 0,
      height: 0,
    },
    textShadowRadius: 4,
  },
  iconHeart: {
    color: ColorLight.white,
  },
  frameContainer: {
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  megaharosh: {
    fontSize: FontSize.headline2_size,
    textShadowColor: "rgba(0, 0, 0, 0.15)",
    textShadowOffset: {
      width: 0,
      height: 4,
    },
    textShadowRadius: 4,
    alignSelf: "stretch",
    flex: 1,
  },
  megaharoshWrapper: {
    backgroundColor: "rgba(51, 51, 51, 0.5)",
    height: 32,
    paddingHorizontal: 12,
    paddingTop: 4,
  },
  frameGroup: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingTop: Padding.p_5xs,
    alignSelf: "stretch",
    justifyContent: "space-between",
    flex: 1,
    //overflow: "hidden",
    borderWidth: 0,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  frameImage: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingTop: Padding.p_5xs,
    alignSelf: "stretch",
    justifyContent: "space-between",
    flex: 1,
    overflow: "hidden",
    borderWidth: 0,
    /*shadowColor: "rgba(0, 0, 0, 0.15)",
     shadowRadius: 6,
     elevation: 6,
     shadowOpacity: 1,
     shadowOffset: {
       width: 0,
       height: 2,
     },*/
  },
  armandoJunctionsCarolyneber: {
    fontFamily: FontFamily.regular,
    marginLeft: 4,
    width: "85%",
    height: 20,
  },
  barbershop: {
    fontWeight: "200",
    width: 248,
    height: 16,
    position: "absolute",
    top: 20,
    left: 2,
    fontFamily: FontFamily.regular,
    fontSize: FontSize.body2_size,
  },
  barbershop1: {
    fontWeight: "200",
    width: 100,
    height: 16,
    position: "absolute",
    top: 20,
    left: 140,
    fontFamily: FontFamily.regular,
    fontSize: FontSize.body2_size,
    textAlign: "right",
  },
  armandoJunctionsCarolyneberParent: {
    alignSelf: "stretch",
    flex: 1,
    flexDirection: "row",
    justifyContent: "left",
  },
  book: {
    fontSize: FontSize.button1_size,
    fontFamily: FontFamily.medium,
    color: ColorLight.white,
    textAlign: "center",
    fontWeight: "500",
    letterSpacing: 0,
    flex: 1,
    textShadowColor: "rgba(0, 0, 0, 0.15)",
    textShadowOffset: {
      width: 0,
      height: 0,
    },
    textShadowRadius: 4,
  },
  bookWrapper: {
    backgroundColor: ColorLight.accentColor,
    width: 88,
    overflow: "hidden",
    alignItems: "center",
    shadowRadius: 4,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    borderRadius: Border.br_5xs,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  frameView: {
    height: 54,
    borderBottomRightRadius: Border.br_5xs,
    borderBottomLeftRadius: Border.br_5xs,
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 12,
    backgroundColor: ColorLight.darkslategray_100,
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  frameParent: {
    height: 224,
    marginTop: 24,
    marginLeft: 24,
    marginRight: 24,
    //overflow: "hidden",
    borderWidth: 0,
    borderRadius: 8,
    borderColor: "black",

    //borderRadius: 32,
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowRadius: 6,
    elevation: 6,
    //height: 40,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  screen1V2: {
    height: 800,
    width: "100%",
    flex: 1,
    backgroundColor: ColorLight.gray,
  },
});

export default stylesLight;
